server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.35.188
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 192.168.35.188
    port: 6381
ly:
  sms:
    accessKeyId: LTAI4qdaJMgFOrou # 你自己的accessKeyId
    accessKeySecret: 1Fny4oQT1xGpXVGaQAmoACgBM0HdPW # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_146802257 # 模板名称