server:
  port: 8090
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.35.188
    port: 6381
  rabbitmq:
    host: 192.168.35.188
    username: guest
    password: guest
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称